# Generated by Django 4.1.2 on 2022-10-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='css_slider',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
